name: CI/CD

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

env:
  NODE_VERSION: "16"

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build -w api
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          workingDirectory: apps/api
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
