name: ci

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

env:
  NODE_VERSION: "16"
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install
        run: npm ci
      - name: Deploy API
        run: npm run deploy