name: CI/CD

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

env:
  NODE_VERSION: "16"

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build -w api
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          PROJECT_PATH: apps/api
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}